import { createSlice } from "@reduxjs/toolkit";
import imageAvartar from "../../assets/imgs/avatar1.png";
import imageAvartar1 from "../../assets/imgs/employee1.png";
import imageAvartar2 from "../../assets/imgs/employee2.png";
import imageAvartar3 from "../../assets/imgs/employee3.png";

import imageSignature from "../../assets/imgs/signature.png";
import imageStamp from "../../assets/imgs/stamp.png";
import { v4 as uuidv4 } from "uuid";
let index = 1;
const initialState = {
  data: [
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 0,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
      online: 1,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 0,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
      online: 0,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
      online: 0,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
      online: 0,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Nguyễn Văn",
      last_name: "Linh",
      email: "vanlinh@example.com",
      phone_number: "(+84) 930238212",
      role: "1",
      date_create: "12/07/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Van Linh",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "20000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar2,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HSDT" + index++,
      first_name: "Lê Cao",
      last_name: "Toàn",
      email: "caotoan123@example.com",
      phone_number: "(+84) 233432123",
      role: "1",
      date_create: "12/05/2021",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Le Cao Toan",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "12000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar3,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Trần Văn",
      last_name: "Quý",
      email: "abc@example.com",
      phone_number: "(+84) 988012355",
      role: "1",
      date_create: "20/07/2020",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Van Quy",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "TBDT" + index++,
      first_name: "Trần Trung",
      last_name: "Sĩ",
      email: "edf@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: false,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Tran Trung Si",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "10000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
    {
      id: "HCTC" + index++,
      first_name: "Đỗ",
      last_name: "Bảo",
      email: "dobao@example.com",
      phone_number: "(+84) 333213221",
      role: "1",
      date_create: "18/07/2019",
      state: true,
      country: "1",
      province: "1",
      district: "2",
      ward: "40",
      code: "1",
      address: "Beu, 423 Điện Biên Phủ",
      card_name: "Do Bao",
      card_number: "19033068505010",
      bank: "Techcombank",
      bank_department: "Phan Đăng Lưu, Bình Thạnh, TPHCM",
      basic_salary: "8000000",
      work_days: "24",
      position: "1",
      department: "1",
      avatar: imageAvartar1,
      signature: imageSignature,
      stamp: imageStamp,
    },
  ],
  auth: {},
  profile: {},
  loginError: null,
  editUser: null,
  setStaffs: null,
};

export const usersReducer = createSlice({
  name: "users",
  initialState,
  reducers: {
    getAuthStart: () => {},
    setAuth: (state, action) => {
      return {
        ...state,
        auth: action.payload,
      };
    },
    setProfile: (state, action) => {
      return {
        ...state,
        profile: action.payload,
      };
    },
    setLoginError: (state, action) => {
      return {
        ...state,
        loginError: action.payload,
      };
    },
    setFunctionUpdateUser: (state, action) => {
      return {
        ...state,
        setStaffs: action.payload,
      };
    },
    setEditUser: (state, action) => {
      return {
        ...state,
        editUser: action.payload,
      };
    },
    setDataUsers: (state, action) => {
      return {
        ...state,
        data: action.payload,
      };
    },
    resetState: () => {
      return initialState;
    },
  },
});

export const {
  getAuthStart,
  setDataUsers,
  setAuth,
  setFunctionUpdateUser,
  setEditUser,
  setLoginError,
  resetState,
  setProfile,
} = usersReducer.actions;

export default usersReducer.reducer;
